[package]
name = "victim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = { version = "3.3.0", optional = true }

[build-dependencies]
toml = "0.5.10"
config = { path = "../config" }

[features]
payload = ["dep:tempfile"]
